### ISSUE TITLE
Que es un gist

### ISSUE THREAD

**Issue by saherla** [AndresVaBa/dev-learning#5]
Buscar que es un gist y crear uno.

Agregar el link  en este issue como comentario 😄

**Comment by AndresVaBa** [comment]
<script src="https://gist.github.com/AndresVaBa/7706dd46ca12b3095a4c63a5b992d0e1.js"></script>

**Comment by andres-vaba** [comment]
<script src="https://gist.github.com/AndresVaBa/7706dd46ca12b3095a4c63a5b992d0e1.js"></script>  :bowtie:  :+1:

**Comment by saherla** [comment]
En el issue #3 agrega este gist usando la notación de markdown para agregar links. El link que comentaste ⬆️ es un `embed` quiere decir que este gist lo puedes colocar en una pagina que acepte JavaScript, para nuestro caso usaremos este link que adjunto en la imagen. Buen trabajo 👍🏻

![Screen Shot 2022-06-29 at 22 51 31](https://user-images.githubusercontent.com/55848425/176589391-9b64568d-b0e5-4323-bfc5-a35db16c5152.png)

**Comment by saherla** [comment]
Unicamente falta agregarlo en la rama donde se encuentra el markdown para ello tienes que cambiar de ramas.

Para saber donde nos encontramos siempre se usa:
`git status`

Para hacer un cambio de rama **ya creada usamos**:
`git checkout nombre-de-mi-rama`

Puedes probar cambiando de ramas, ejemplo:

`git checkout main`
`git checkout nombrado`

Tienes que ir a la rama donde se encuentra el archivo que necesitas editar y agregar el link de tu gist usando el link share mostrado en la imagen de arriba ⬆️, tambien tienes que arreglar esta linea [aquí](https://github.com/AndresVaBa/dev-learning/commit/71985ce94404a07450533f593ccfcede948a0e0c#r77429372)

Por ultimo tu commit tiene que ser escrito con conventional commits

`git commit -m "fix: aqui debe de ir una breve explicación de lo que hiciste o resolviste"`

Es importante esta notación por que luego agregaremos una herramienta que obligara a que los commits los hagas tal cual como los pide conventional commits y te marcara error siempre que trates de hacer un push.
